### ISSUE TITLE
API upload Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by japorized** [Lugarun/salz#22]
## Steps to reproduce

1. Go to branch [front-end](https://github.com/Lugarun/salz/tree/d4750d9642690f665a7598b262fb0ef72964e50c)
2. Spin up docker for api and engine, run `npm run dev` from `salz-web/`.
3. Login (if you have not)
4. Click on your username on Navbar
5. Try to upload a bot and hit submit.

## Screenshot
![2019-11-01-212137](https://user-images.githubusercontent.com/1314543/68064099-b4116b80-fced-11e9-9778-fa202309108f.png)

Note: Not to be confused with #3

**Comment by mosiman** [comment]
![SatNov02_19_133848](https://user-images.githubusercontent.com/16958825/68074845-87edfd00-fd76-11e9-9346-64552f2a6e43.png)

no CORS on my end but i gotta investigate the server error

**Comment by mosiman** [comment]
xd the cors error is in the console tab

**Comment by mosiman** [comment]
The front end is making a POST request with content type `application/json`, we should have it be a `multipart/form-data`
@japorized

**Comment by mosiman** [comment]
The CORS error happens when there's a API server error and the debug page is thrown, which doesn't have the appropriate CORS headers. 

Johnson if this is fixed, closeity close?

**Comment by japorized** [comment]
Yep. The other related #25 is there so we can close this.
