### ISSUE TITLE
API returns TypeError when there is no game data

### ISSUE THREAD

**Issue by japorized** [Lugarun/salz#23]
Error log in following screenshot:

![image](https://user-images.githubusercontent.com/1314543/68076933-b1685200-fd91-11e9-894a-c5d4cae98351.png)

**Comment by mosiman** [comment]
this screenshot is less shit

![MonNov04_19_123832](https://user-images.githubusercontent.com/16958825/68143732-12159d00-ff00-11e9-83a4-4f4aabab40b5.png)

**Comment by mosiman** [comment]
should be fixed in 4fea7fb
