### ISSUE TITLE
[game-engine] [api] [front-end] Reduce large game history storage.

### ISSUE THREAD

**Issue by Lugarun** [Lugarun/salz#24]
Currently:
We are representing the game history in the naive way everywhere (as the coordinates of every cell in every frame). This is bad because it takes up tons of space. It takes tons of storage and lots of bandwidth.

Desired:
Instead we should represent the history by checkpoint frames, and all player commands between these frames. This will cut down storage and bandwidth drastically. The downside is that everywhere you want to be able to interpret the history you need to implement conways game of life.

**Comment by mosiman** [comment]
F

**Comment by japorized** [comment]
Hard problem that I’m still trying to figure out a good way to do this. But if we move forward with the new idea (I can’t seem to find the issue number on Github mobile), things may change.

In any case, **F** indeed.

**Comment by Lugarun** [comment]
I started working on this in the map-representation branch

**Comment by Lugarun** [comment]
A new map representation uses a fraction of the storage, it is also way less information for the client to download from the server.

The database has been updated to the new map representation: b9e96f30cff25366331c87e655026d65206d515a

**Comment by japorized** [comment]
Just to make the note here. This change forces any game client to implement the game rules on their end.
