### ISSUE TITLE
Replace Pixi.js, Pixi Viewport, and Hotkeys.js with Phaser.js

### ISSUE THREAD

**Issue by japorized** [Lugarun/salz#37]
I'm thinking it's been quite messy on my end having to do lots of scaffolding for Pixi.js to be a good game UI renderer, having to fake a grid system, hotkeys blends in so much with the non-game UI etc. Many of these stuff are done quite inefficiently, mostly due to my lack of experience and knowledge which leads to writing many important code in an inefficient way.

I know that this is sort of like pushing away my responsibilities, but I'm thinking of letting [Phaser](https://github.com/photonstorm/phaser) do away a lot of the heavy lifting for me. Pixi.js is great, but I'm spending too much time trying to get things to work with it. Pixi.js is a rendering library, and is nothing more than that. Phaser is a game library with many of the batteries that we want included.

So I'd like propose trying out Phaser. If it does indeed make things a whole lot easier for us, and even for you guys (@mosiman and @Lugarun) to hop on, then we can decide if we want to stick with it and drop Pixi.js.

**Comment by mosiman** [comment]
I've used phaser before... Once... Im okay with this. It would probably add some bloat to the build, but whatever

**Comment by japorized** [comment]
It’s going to be bloated either way unless if we do everything from scratch anyways, but I’m not capable of that right now.

I’ll see if Phaser lets us pick their features as like modules. That should reduce the final build size if that’s a thing, but we’ll see.

**Comment by mosiman** [comment]
I say fuck it, let's just get something out and try to reduce the size later on.

**Comment by japorized** [comment]
We don’t necessarily have to switch, cause there’s a lot of unknown on how well Phaser would fit our bill. So far early in my trials, it doesn’t seem to fit too well.
